plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Gemspec/RequireMFA:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

RSpec/DescribedClass:
  Enabled: false
